# Generated by Django 3.2.9 on 2021-11-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=70)),
                ('titulo', models.CharField(max_length=70)),
                ('orirentador', models.CharField(max_length=70)),
                ('coorientador', models.CharField(blank=True, max_length=70, null=True)),
                ('area_do_conhecimento', models.CharField(max_length=50)),
                ('data_publicacao', models.DateField()),
                ('palavras_chaves', models.CharField(max_length=100)),
            ],
        ),
    ]
